name: publish
on:
  push:
    branches: [master]

env:
  CI: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@firaenix'

      - name: Configure CI Git User
        run: |
          git config --global user.name 'firaenix'
          git config --global user.email 'firaenix@users.noreply.github.com'

      - name: Install
        run: yarn install

      - name: Publish
        run: |
          npm whoami
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > ~/.npmrc
          yarn lerna publish from-package --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
