name: version
on:
  push:
    branches:
      - 'master'

env:
  CI: true

jobs:
  publish:
    name: Version
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@firaenix'

      - name: Configure CI Git User
        run: |
          git config --global user.name 'firaenix'
          git config --global user.email 'firaenix@users.noreply.github.com'

      - name: Install Lerna
        run: yarn install

      - name: Publish
        run: yarn lerna version prerelease --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
